name = "Qt5Tools_jll"
uuid = "a9c6e4b1-b2fb-56d5-96a9-25f276f13840"
version = "5.15.2+1"

[deps]
Qt5Base_jll = "ea2cea3b-5b76-57ae-a6ef-0a8af62496e1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Glib_jll = "7746bdde-850d-59dc-9ae8-88ece973131d"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.2.0"
julia = "1.0"
